name: CI for Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    # Run tests with Xvfb for Linux systems to emulate a display environment
    - name: Run tests on Linux with Xvfb
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test

    # Run tests on macOS and Windows without Xvfb
    - name: Run tests
      if: runner.os != 'Linux'
      run: npm test

    - name: Lint
      run: npm run lint

    - name: Build the extension
      run: npm run vscode:prepublish

    - name: Package the extension
      run: npx @vscode/vsce package
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}